apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: spring-petclinic
  namespace: spring-petclinic
spec:
  serviceAccountName: spring-petclinic-ns-sa
  fetch:
  - git:
      url: https://github.com/pkhamdee/kapp-controller-apps.git
      ref: origin/master
      subPath: spring-petclinic
  template:
  - ytt: {}
  - kbld: {}
  deploy:
  - kapp: {}